// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqnndwfntcvcccrmrbzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xbm5kd2ZudGN2Y2Njcm1yYnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODU1NjgsImV4cCI6MjA2NDI2MTU2OH0.rTlYEn2k5bci_zeWhf-_N85aNkZAmMya1ZltaZndpNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);